AUG:
    RESIZE_METHOD: 'stepscaling' # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: [720, 720] # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    TRAIN_CROP_SIZE: [512, 256]  # crop size for training
    EVAL_CROP_SIZE: [512, 256]  # crop size for evaluating
    CROP_PAD_SIZE: 32
    MIRROR: True
    FLIP: False
    FLIP_RATIO: 0.5
    RICH_CROP:
        ENABLE: False
        BLUR: True
        BLUR_RATIO: 0.2
        MAX_ROTATION: 15
        MIN_AREA_RATIO: 0.5
        ASPECT_RATIO: 0.5
        BRIGHTNESS_JITTER_RATIO: 0.5
        CONTRAST_JITTER_RATIO: 0.5
        SATURATION_JITTER_RATIO: 0.5
DATASET:
    DATA_DIR: '/home/user/lanenet/data/training_data_example/'
    IMAGE_TYPE: 'rgb'  # choice rgb or rgba
    NUM_CLASSES: 2
    TEST_FILE_LIST: '/home/user/lanenet/data/training_data_example/test.txt'
    TRAIN_FILE_LIST: '/home/user/lanenet/data/training_data_example/train.txt'
    VAL_FILE_LIST: '/home/user/lanenet/data/training_data_example/val.txt'
    IGNORE_INDEX: 255
    PADDING_VALUE: [127.5, 127.5, 127.5]
    MEAN_VALUE: [0.5, 0.5, 0.5]
    STD_VALUE: [0.5, 0.5, 0.5]
    CPU_MULTI_PROCESS_NUMS: 8
FREEZE:
    MODEL_FILENAME: 'model'
    PARAMS_FILENAME: 'params'
MODEL:
    MODEL_NAME: 'lanenet'
    FRONT_END: 'bisenetv2'
    EMBEDDING_FEATS_DIMS: 4
    BISENETV2:
        GE_EXPAND_RATIO: 6
        SEMANTIC_CHANNEL_LAMBDA: 0.25
        SEGHEAD_CHANNEL_EXPAND_RATIO: 2
TEST:
    TEST_MODEL: 'model/cityscapes/final'
    IPM_REMAP_FILE_PATH : '/home/user/lanenet/data/weight/tusimple_ipm_remap.yml'    
TRAIN:
    MODEL_SAVE_DIR: 'result_train/weights/tusimple/'
    TBOARD_SAVE_DIR: 'result_train/tboard/tusimple/'
    MODEL_PARAMS_CONFIG_FILE_NAME: "model_train_config.json"
    RESTORE_FROM_SNAPSHOT: # transfer learning 할 수 있는 부분
        ENABLE: True  
        SNAPSHOT_PATH: '/home/user/lanenet/data/weight/tusimple_lanenet.ckpt'
    SNAPSHOT_EPOCH: 8
    BATCH_SIZE: 32
    VAL_BATCH_SIZE: 4
    VAL_TEST : False  # 내가 early stopping 할려고 추가한 것. 
    EPOCH_NUMS: 905
    WARM_UP:
        ENABLE: True
        EPOCH_NUMS: 8
    FREEZE_BN:
        ENABLE: False
    COMPUTE_MIOU:
        ENABLE: True
        EPOCH: 1
    MULTI_GPU:
        ENABLE: FALSE
        GPU_DEVICES: ['0', '1']
        CHIEF_DEVICE_INDEX: 0
SOLVER:
    LR: 0.001
    LR_POLICY: 'poly'
    LR_POLYNOMIAL_POWER: 0.9
    OPTIMIZER: 'sgd'
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    MOVING_AVE_DECAY: 0.9995
    LOSS_TYPE: 'cross_entropy'
    OHEM:
        ENABLE: False
        SCORE_THRESH: 0.65
        MIN_SAMPLE_NUMS: 65536
GPU:
    GPU_MEMORY_FRACTION: 0.9 # GPU가 할당되어야 하는 전체 메모리 양의 비율
    TF_ALLOW_GROWTH: True  # 더 많은 GPU 메모리가 필요할 때, GPU 메모리 영역 확장
POSTPROCESS:
    MIN_AREA_THRESHOLD: 100
    DBSCAN_EPS: 0.35
    DBSCAN_MIN_SAMPLES: 350
LOG:
    SAVE_DIR: './log'
    LEVEL: INFO
